// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCijutxnwkyyTIHGTe6aBzypUovC24vOt4',
    appId: '1:215342272560:web:a6ce7e6c0b7ece90fd1df5',
    messagingSenderId: '215342272560',
    projectId: 'hamging-dd902',
    authDomain: 'hamging-dd902.firebaseapp.com',
    storageBucket: 'hamging-dd902.appspot.com',
    measurementId: 'G-N24K453K60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYij9IkP1C-MxGQPbR9Cyfyea-zqhDVb4',
    appId: '1:215342272560:android:5236e3b6484e4e3cfd1df5',
    messagingSenderId: '215342272560',
    projectId: 'hamging-dd902',
    storageBucket: 'hamging-dd902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDerZCA_hVJmtHXguTaE8tb-mFZNNoSlT8',
    appId: '1:215342272560:ios:246404c90a29b835fd1df5',
    messagingSenderId: '215342272560',
    projectId: 'hamging-dd902',
    storageBucket: 'hamging-dd902.appspot.com',
    iosBundleId: 'com.example.flutterBlock',
  );
}
